# Generated by Django 4.1.4 on 2023-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=20)),
                ('mileage', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
    ]
